/* ========================================
 *  This file was generated by: https://github.com/iffyloop/EasyAirwindows
 * ======================================== */

#pragma once

#include <EasyAirwindows/EasyAirwindowsAudioEffectX.h>

namespace EasyAirwindows {

namespace Index {

extern const int NUM_EFFECT_IDS;

extern const char * const getEffectName(int effectId);
extern EasyAirwindowsAudioEffectX *createEffect(int effectId);
extern void destroyEffect(EasyAirwindowsAudioEffectX *effect);

}

}
